# Generated by Django 3.2.9 on 2022-06-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myform', '0003_auto_20220614_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsmodel',
            options={'verbose_name': 'informations'},
        ),
        migrations.AlterModelTable(
            name='formsmodel',
            table=None,
        ),
    ]
