# Generated by Django 3.2.9 on 2022-06-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myform', '0004_auto_20220614_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsmodel',
            options={'ordering': ['name'], 'verbose_name': 'informations'},
        ),
        migrations.AddField(
            model_name='formsmodel',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formsmodel',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formsmodel',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formsmodel',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='formsmodel',
            table='idkkk',
        ),
    ]
